### ISSUE TITLE
Plugin loading on Windows does not work (code 126)

### ISSUE THREAD

**Issue by rubyglow** [rubyglow/racktool#2]
On Mac and Linux loading plugins works just fine. On Windows (7 and 10) however it does not work, and *always* fails with code 126, no matter which plugin you try to load. It's extremely frustrating, especially since the loader code is the same as in Rack. If you can diagnose or fix this you're a real hero :-)

The error occurs in the LoadLibrary() call and the error from the Windows API is: [126] The specified module could not be found. Note that "module" has nothing to do with a Rack module, it's Windows lingo for a .dll. The call is located in dep/rackproxy/src/pluginwrapper.cpp line 32.

A couple of examples from trying on a Windows console:

rackproxy plugin c:\Users\labj\Source\rackdev\plugins\Template

{"dir": "c:\\Users\\labj\\Source\\rackdev\\plugins\\Template", "file": "c:\\Users\\labj\\Source\\rackdev\\plugins\\Template/plugin.dll", "loaded": false, "loadError": "Failed to load plugin c:\\Users\\labj\\Source\\rackdev\\plugins\\Template/plugin.dll: [126] The specified module could not be found. "}

rackproxy plugin c:/Users/labj/Source/rackdev/plugins/Template

{"dir": "c:/Users/labj/Source/rackdev/plugins/Template", "file": "c:/Users/labj/Source/rackdev/plugins/Template/plugin.dll", "loaded": false, "loadError": "Failed to load plugin c:/Users/labj/Source/rackdev/plugins/Template/plugin.dll: [126] The specified module could not be found. "}

**Comment by rubyglow** [comment]
I should also note that I have tried a different building approach than the current, to see if it would help. I tried a different version of the makefile, where instead of (like now) linking against the Rack *objects*, I build with the Rack *sourcecode*. It made no difference at all :-(

**Comment by rubyglow** [comment]
One thing I have tried on Windows, is to trace the entire loading process in detail, using the brilliant tool Procmon.exe from https://live.sysinternals.com/

Try and run Procmon.exe, and open menu Filter -> Filter
Set: Process name is rackproxy.exe
And click Ok
Then menu Edit -> Clear display

Now run e.g: rackproxy.exe plugin %USERPROFILE%\Documents\Rack\plugins\Fundamental

Procmon now shows the entire (huge) Windows loading process involved. Maybe you'll be better at reading it than me and see something I don't. One thing I find very interesting is that about 2/3'rds down you'll find (on my system): Load Image SUCCESS on C:\Users\labj\Documents\Rack\plugins\Fundamental\plugin.dll

That indicates to me, that *actually* the plugin *did* get loaded without problems. Very strange.

But the weirdest thing I think, is that right below that, you'll see CreateFile attempts of {Various paths}\Rack.exe. What on earth? Where is there a memory of *anything* Rack.exe? When on my Mac I do "strings rackproxy.exe" the only thing ".exe" is "rackproxy.exe". Very strange!

**Comment by rubyglow** [comment]
Hi Bruce

Thanks for building and testing!

Just to adress the last part first: The mixed slashes are exactly how Rack does it, and Windows is just fine with that. Look in your documents\Rack\log.txt file if you don't believe me :-)

No, that's not it...

Your result is a step forward but, alas, not the solution. I've actually been there before, but let me explain....

Putting rackdev\Rack-0.6.1\dep\lib in the PATH does absolutely nothing at all, and it shouldn't because Rack and rackproxy are completely statically linked with those libraries in version 0.6.1, so they're not needed at runtime. That's why Rack.exe and rackproxy.exe are *huge* before being stripped.

Putting rackdev\Rack-0.6.1 in the PATH *does* make a difference, and this is where the weird part starts....

Further up in this thread, you'll notice that when I do a trace of the loading process, I'm bewildered to see it trying to open "Rack.exe"; what on earth is that about?

And this is where putting rackdev\Rack-0.6.1 in the PATH has an effect, because the loading process finds Rack.exe there. If you don't believe me, try this:

In rackdev\Rack-0.6.1\ try and rename Rack.exe to e.g. Rack.exe.NOPE, and then run again. Now you'll see the old code 126 message back, because it *can't find Rack.exe in the PATH anymore*!

Now try in rackdev\Rack-0.6.1\ and create an empty Rack.exe file (by doing e.g. touch Rack.exe). Now you get: [193] %1 is not a valid Win32 application - again, because Windows is trying to load Rack.exe but finds nonsense.

As a last experiment, try and copy rackproxy.exe to rackdev\Rack-0.6.1\Rack.exe, and run again. Now you get: [127] The specified procedure could not be found. This might actually hold a deeper clue....

So, the problem is not solved, because running rackproxy.exe causes Windows to try and load Rack.exe, which it definately shouldn't do, and is quite a mystery to me.

But your result is progress in terms of debugging, because you are actually able to succesfully load a plugin with rackproxy.exe, as long as Rack.exe can be found. There's a linking and loading mystery waiting to be solved there.

I never got that far, because when I tried/try the same, I get the standard Windows "your program crashed, looking for a solution..." error window, and I *suspect* that the reason it works for you, is that you are on a physical computer where Rack can actually run. My Windows machine is a Virtualbox VM, and unfortunately Rack does not run in it, because Virtualbox does not supply uptodate WDM drivers (or something) that enables OpenGL applications to work, bummer :-)

So a step closer, but not really solved. The mystery lies in the question: What causes the way I link rackproxy on Windows, the runtime system to then need Rack.exe, which it definately shouldn't. There's something very weird going on, and I hope the answer doesn't turn out to be "MinGW linking bug", or somethink like that.

If you can dig deeper, maybe with the help of procmon described above, or get any other brilliant ideas, it'd be much appreciated Bruce!

Cheers

**Comment by squinkylabs** [comment]
Download dependency walker, and run it on a plugin. I see that Fundamental (and other) does, in fact, link to Rack.exe. Andrew always mentions this - I would ask him about it.
![rack](https://user-images.githubusercontent.com/16314838/41812500-acbdd586-76d8-11e8-8a8b-0e9f11e0208f.png)

**Comment by rubyglow** [comment]
Sure, plugins are not statically linked - they're dynamic libraries, and get all their symbols satisfied by the Rack application. Look in the installation directory for Rack 0.6.1 on Windows ("c:\Program Files\VCV\Rack\"). The only libraries it needs are the 3 MinGW runtime libraries. This is a change from 0.6.0.

The repro case is trying to load any Rack plugin. I tried making the simplest possible Rack plugin, just to rule other factors out. It loads in Rack and I have attached the .zip with source+plugin binaries.
[Simplest.zip](https://github.com/rubyglow/racktool/files/2130126/Simplest.zip)

**Comment by rubyglow** [comment]
HOT DAMN... you are correct! When I run strings on my "Simplest" plugin, sure enough, there I find Rack.exe. That's.... strange. Any clue why?

**Comment by squinkylabs** [comment]
Look at the symbols on the right side of the illo. All of the controls that you use for UI, etc...

**Comment by rubyglow** [comment]
I find that really strange, but now that I think about it - on Windows, as opposed to Mac and Linux, plugins are linked against the generated libRack.a library, and because of that it probably gets a Rack.exe symbol in there...

**Comment by rubyglow** [comment]
The thing I don't quite get is: Why does renaming rackproxy.exe to Rack.exe not solve the problem? Because then you get: [127] The specified procedure could not be found
Simply because of different symbol ordering between rackproxy and libRack.a? Or does rackproxy miss some symbols used by plugins, *only* on Windows, that are not used on Mac and Lin?

**Comment by rubyglow** [comment]
Yup, running strings on libRack.a shows lots of "Rack.exe" in there. Hmm....  what to do?

**Comment by rubyglow** [comment]
Also just tried making a copy of rackproxy.exe to Rack.exe in the same directory, and I get "[127] The specified procedure could not be found". So something about symbols present in libRack.a, that are not present in rackproxy, that plugins under Windows get linked against, and thus have to find, even though they might not need them. The only thing that gets excluded from the rackproxy build, compared to Rack, are those from Rack-0.6.1/build/src/main.cpp.o. They have to be, because you can't have two main() functions in the program. But main() *is* the only function in there, no other symbols, and plugins don't need main() to load or run, so I'm kinda baffled by this.

**Comment by rubyglow** [comment]
Quote: He does always mention, when someone proposes a plugin loader, "but plugins link to rack. you would need to duplicate all of rack". Yup, I remember that, and that's what I thought I'd done in rackproxy, because it basically *links in* all of Rack (excluding main()). And it works fine on Mac and Lin :-( But yeah, I guess "plugins link to rack" can be taken VERY literally :-( I guess the "solution" can be to simply include a copy of Rack.exe from the rack build, alongside rackproxy on Windows, if that's what it takes to make it "work" :-/

**Comment by squinkylabs** [comment]
If you fire up dependency walker, it lists all the symbols it's looking for in Rack.exe. Notice in my illo are some light widgets and param widgets. Surely you don't have those in your rackproxy?

All linking should be done by name, not index.

I've never tried renaming something to try to fool the linker. Maybe the .a file does have info specific to Rack.exe...

But I think the first question is - do you export all the entry points that rack does? I doubt it - you would need all of rack in your exe. I'm suspecting the only way to get this to work is to actually let the plugins find rack.exe. Is there a reason you can't do this?As you say, it seems to work ok on real windows and other OS. Why do you need to run in dosbox?

**Comment by rubyglow** [comment]
If you look at my Makefile, rackproxy is basically built by linking in *every single* object (the .o files) from Rack, with the exception of the main() function. So yeah, rackproxy contains all of rack, and it can load all rack plugins, on mac and linux that is.

**Comment by rubyglow** [comment]
I build for Linux and Windows in a Virtualbox VM, because I don't have a physical machine to spare right now for it. But I guess I can be forced to buy one... :-)

**Comment by squinkylabs** [comment]
ah, right. Ok, that's a bit of a mystery. is there any way I can observe it not working? I guess you are saying that if I delete my Rack.exe I will see your problem?

**Comment by rubyglow** [comment]
Yes, that's what I'm saying. You'll immediately get the code 126 error if you remove Rack.exe from the PATH.

**Comment by squinkylabs** [comment]
yes seeing that now.

**Comment by squinkylabs** [comment]
So here's what I can tell with a quick look. your exe does not export all the entry points that Rack.exe does.  Rack exports TONs more. Use DLL export viewer to examine them. I downloaded it from here: http://www.nirsoft.net/utils/dll_export_viewer.html.

As to why.... I don't know. Maybe the linker only exports things that you use? Maybe there is some flag to tell it to export everything? 

I see that Rack.exe exports 13,936 functions. racktool only exports 48.

Don't get too worked up about all this. This is pretty nitty gritty stuff, and there's no reason to thing that a bug in the tools is the cause of this. Everything so far seems sane.

**Comment by rubyglow** [comment]
Hmm, strange. Because I build it with all the rack symbols linked in, and the exe size is the same as Rack's. I'm not stiff on the whole "exported" thing in Windows. I guess I'll have to look into that. Thanks Bruce!

**Comment by squinkylabs** [comment]
you'll get it!

**Comment by rubyglow** [comment]
Only thing left now is to try and use the name rackproxy.exe rather than being forced to use rack.exe. I'll probably try and look into Windows manifests for executables, which I vaguely remember reading about once.

**Comment by rubyglow** [comment]
I'm closing this since plugin loading on Windows actually *works* now. Thanks again for your help Bruce! I have created issue #3 for the remaining minor/cosmetic issue, regarding the executable name.
